"""
Scenario Templates
AI Language Tutor App

Contains both:
1. Session 131 scenario builder templates (SCENARIO_TEMPLATES dictionary)
2. Factory scenario templates (ScenarioTemplates class for UniversalScenarioTemplate)
"""

from typing import Dict, List, Optional

from .scenario_models import (
    ScenarioCategory,
    UniversalScenarioTemplate,
)

# Template data structure
SCENARIO_TEMPLATES: Dict[str, Dict] = {
    "template_restaurant_basic": {
        "template_id": "template_restaurant_basic",
        "title": "Restaurant Dining Experience",
        "description": "Practice ordering food, making requests, and handling payment at a restaurant",
        "category": "restaurant",
        "difficulty": "beginner",
        "estimated_duration": 15,
        "language": "en",
        "user_role": "customer",
        "ai_role": "server/waiter",
        "setting": "A casual dining restaurant",
        "prerequisites": ["basic_greetings", "numbers", "common_food_items"],
        "learning_outcomes": [
            "Order meals confidently",
            "Make polite requests",
            "Handle restaurant payment",
            "Understand menu terminology",
        ],
        "vocabulary_focus": [
            "menu",
            "order",
            "appetizer",
            "entree",
            "dessert",
            "drink",
            "water",
            "check",
            "tip",
            "reservation",
        ],
        "cultural_context": {
            "tipping": "In many Western countries, 15-20% tip is customary",
            "service": "Wait staff typically check on you periodically",
            "payment": "You usually pay after the meal",
        },
        "phases": [
            {
                "name": "Arrival and Seating",
                "description": "Greet the host and get seated at a table",
                "expected_duration_minutes": 3,
                "key_vocabulary": ["table", "party", "reservation", "seat", "host"],
                "essential_phrases": [
                    "Table for two, please",
                    "Do you have a reservation?",
                    "This way, please",
                    "Follow me",
                ],
                "learning_objectives": [
                    "Request a table politely",
                    "Provide party size information",
                    "Understand seating options",
                ],
                "success_criteria": [
                    "Successfully request seating",
                    "Communicate party size",
                    "Confirm seating preference",
                ],
                "cultural_notes": "Wait to be seated in most formal restaurants; in casual places, you may seat yourself",
            },
            {
                "name": "Ordering Food",
                "description": "Review the menu and place your order",
                "expected_duration_minutes": 6,
                "key_vocabulary": [
                    "appetizer",
                    "main course",
                    "side dish",
                    "beverage",
                    "allergies",
                    "recommendations",
                ],
                "essential_phrases": [
                    "I'll have the...",
                    "What do you recommend?",
                    "I'm allergic to...",
                    "Can I get that without...?",
                ],
                "learning_objectives": [
                    "Ask for recommendations",
                    "Place a complete order",
                    "Communicate dietary restrictions",
                ],
                "success_criteria": [
                    "Order appetizer, main, and drink",
                    "Ask at least one question about the menu",
                    "Make a special request or substitution",
                ],
                "cultural_notes": "It's acceptable to ask questions about dishes; servers expect it",
            },
            {
                "name": "During the Meal",
                "description": "Interact with server during dining, make requests",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "napkin",
                    "utensils",
                    "refill",
                    "condiments",
                    "complaint",
                ],
                "essential_phrases": [
                    "Could I have more water?",
                    "This is delicious!",
                    "Excuse me, could we get...?",
                    "There seems to be a problem with...",
                ],
                "learning_objectives": [
                    "Make polite requests during meal",
                    "Handle issues professionally",
                    "Express satisfaction or concerns",
                ],
                "success_criteria": [
                    "Make at least one request",
                    "Respond to server's check-in",
                    "Use polite language throughout",
                ],
                "cultural_notes": "Servers typically check if everything is okay partway through the meal",
            },
            {
                "name": "Payment and Departure",
                "description": "Request the check, pay, and leave",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "check",
                    "bill",
                    "tip",
                    "credit card",
                    "change",
                    "receipt",
                ],
                "essential_phrases": [
                    "Could we have the check, please?",
                    "Is the tip included?",
                    "Keep the change",
                    "Thank you for everything",
                ],
                "learning_objectives": [
                    "Request the check properly",
                    "Handle payment transaction",
                    "Calculate and leave appropriate tip",
                ],
                "success_criteria": [
                    "Request the check",
                    "Complete payment",
                    "Thank the staff",
                ],
                "cultural_notes": "Tipping is expected in the US (15-20%); in some countries, service is included",
            },
        ],
    },
    "template_travel_hotel": {
        "template_id": "template_travel_hotel",
        "title": "Hotel Check-in and Stay",
        "description": "Navigate hotel check-in, room requests, and hotel services",
        "category": "travel",
        "difficulty": "intermediate",
        "estimated_duration": 20,
        "language": "en",
        "user_role": "hotel guest",
        "ai_role": "hotel staff",
        "setting": "Hotel reception and facilities",
        "prerequisites": ["basic_conversation", "numbers", "dates_times"],
        "learning_outcomes": [
            "Complete hotel check-in process",
            "Request hotel services",
            "Handle accommodation issues",
            "Use hotel facilities confidently",
        ],
        "vocabulary_focus": [
            "reservation",
            "confirmation",
            "check-in",
            "check-out",
            "room type",
            "amenities",
            "concierge",
            "luggage",
            "Wi-Fi",
            "housekeeping",
        ],
        "cultural_context": {
            "tipping": "Tip bellhops and housekeeping in many countries",
            "check_in_time": "Standard check-in is usually 3-4 PM",
            "requests": "Most reasonable requests can be accommodated",
        },
        "phases": [
            {
                "name": "Arrival and Check-in",
                "description": "Check in at the hotel reception desk",
                "expected_duration_minutes": 5,
                "key_vocabulary": [
                    "reservation",
                    "passport",
                    "credit card",
                    "room key",
                    "confirmation number",
                    "booking",
                ],
                "essential_phrases": [
                    "I have a reservation under...",
                    "Here's my confirmation number",
                    "What time is breakfast served?",
                    "Is Wi-Fi included?",
                ],
                "learning_objectives": [
                    "Provide reservation details",
                    "Ask about hotel services",
                    "Understand check-in procedures",
                ],
                "success_criteria": [
                    "Present reservation information",
                    "Complete registration form",
                    "Ask about facilities",
                ],
                "cultural_notes": "Have passport and credit card ready; credit card is usually required for incidentals",
            },
            {
                "name": "Room Inspection",
                "description": "Check the room and report any issues",
                "expected_duration_minutes": 4,
                "key_vocabulary": [
                    "air conditioning",
                    "heating",
                    "view",
                    "bathroom",
                    "towels",
                    "problem",
                    "upgrade",
                ],
                "essential_phrases": [
                    "The AC isn't working",
                    "Could I get extra towels?",
                    "Is a room upgrade available?",
                    "The room smells musty",
                ],
                "learning_objectives": [
                    "Identify room problems",
                    "Request room changes",
                    "Ask for room upgrades",
                ],
                "success_criteria": [
                    "Inspect room amenities",
                    "Report an issue politely",
                    "Request needed items",
                ],
                "cultural_notes": "It's reasonable to request a room change if there are significant problems",
            },
            {
                "name": "Using Hotel Services",
                "description": "Request hotel amenities and services",
                "expected_duration_minutes": 6,
                "key_vocabulary": [
                    "room service",
                    "laundry",
                    "concierge",
                    "restaurant",
                    "gym",
                    "pool",
                    "spa",
                    "tour",
                ],
                "essential_phrases": [
                    "I'd like to book a spa treatment",
                    "Can you recommend a nearby restaurant?",
                    "What time does the gym close?",
                    "I need laundry service",
                ],
                "learning_objectives": [
                    "Request hotel services",
                    "Ask for local recommendations",
                    "Make reservations",
                ],
                "success_criteria": [
                    "Request at least two services",
                    "Ask about facility hours",
                    "Get local information from concierge",
                ],
                "cultural_notes": "Concierge can help with tours, restaurant reservations, and local tips",
            },
            {
                "name": "Check-out",
                "description": "Settle your bill and check out",
                "expected_duration_minutes": 5,
                "key_vocabulary": [
                    "bill",
                    "charges",
                    "minibar",
                    "late check-out",
                    "luggage storage",
                    "receipt",
                ],
                "essential_phrases": [
                    "I'd like to check out, please",
                    "Can I review the charges?",
                    "Is late check-out available?",
                    "Can I leave my luggage here?",
                ],
                "learning_objectives": [
                    "Review and settle hotel bill",
                    "Request late check-out",
                    "Arrange luggage storage",
                ],
                "success_criteria": [
                    "Review bill for accuracy",
                    "Complete payment",
                    "Return room key",
                ],
                "cultural_notes": "Review bill carefully; late check-out may incur extra charges",
            },
        ],
    },
    "template_shopping_clothing": {
        "template_id": "template_shopping_clothing",
        "title": "Clothing Shopping",
        "description": "Shop for clothes, try on items, and make purchases",
        "category": "shopping",
        "difficulty": "beginner",
        "estimated_duration": 15,
        "language": "en",
        "user_role": "shopper",
        "ai_role": "sales associate",
        "setting": "Clothing store",
        "prerequisites": ["numbers", "colors", "basic_adjectives"],
        "learning_outcomes": [
            "Ask for sizes and styles",
            "Try on clothing",
            "Express preferences",
            "Complete purchases",
        ],
        "vocabulary_focus": [
            "size",
            "color",
            "fit",
            "style",
            "fitting room",
            "discount",
            "receipt",
            "return policy",
            "sale",
            "price tag",
        ],
        "cultural_context": {
            "sizing": "Sizes vary by country (US vs EU vs UK)",
            "trying_on": "Always allowed to try on clothes",
            "returns": "Most stores have return policies",
        },
        "phases": [
            {
                "name": "Browsing and Asking for Help",
                "description": "Look for items and ask for assistance",
                "expected_duration_minutes": 4,
                "key_vocabulary": [
                    "section",
                    "department",
                    "looking for",
                    "show me",
                    "style",
                ],
                "essential_phrases": [
                    "I'm looking for...",
                    "Do you have this in a different color?",
                    "Where is the... section?",
                    "Can you help me find...?",
                ],
                "learning_objectives": [
                    "Ask for specific items",
                    "Describe what you're looking for",
                    "Navigate store sections",
                ],
                "success_criteria": [
                    "Ask for assistance",
                    "Describe desired item",
                    "Locate appropriate section",
                ],
                "cultural_notes": "Sales associates expect to help you; don't hesitate to ask",
            },
            {
                "name": "Trying On Clothes",
                "description": "Use fitting room and assess fit",
                "expected_duration_minutes": 5,
                "key_vocabulary": [
                    "fitting room",
                    "too tight",
                    "too loose",
                    "perfect fit",
                    "different size",
                    "mirror",
                ],
                "essential_phrases": [
                    "Can I try this on?",
                    "Do you have a larger/smaller size?",
                    "This is too tight/loose",
                    "How does this look?",
                ],
                "learning_objectives": [
                    "Request to use fitting room",
                    "Ask for different sizes",
                    "Express fit preferences",
                ],
                "success_criteria": [
                    "Try on at least one item",
                    "Request different size if needed",
                    "Describe fit accurately",
                ],
                "cultural_notes": "You can take multiple items to try; no obligation to buy",
            },
            {
                "name": "Making a Decision",
                "description": "Decide on purchase and ask questions",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "price",
                    "on sale",
                    "discount",
                    "deal",
                    "expensive",
                    "cheap",
                ],
                "essential_phrases": [
                    "How much is this?",
                    "Is this on sale?",
                    "Do you have any discounts?",
                    "I'll take it",
                ],
                "learning_objectives": [
                    "Ask about prices",
                    "Inquire about sales",
                    "Make purchase decision",
                ],
                "success_criteria": [
                    "Ask about price or discount",
                    "Decide to buy or not",
                    "Explain decision if declining",
                ],
                "cultural_notes": "Asking about sales and discounts is perfectly acceptable",
            },
            {
                "name": "Checkout and Payment",
                "description": "Pay for items and understand policies",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "cash",
                    "card",
                    "receipt",
                    "return",
                    "exchange",
                    "warranty",
                ],
                "essential_phrases": [
                    "I'll pay with card/cash",
                    "What's your return policy?",
                    "Can I get a receipt?",
                    "Do you gift wrap?",
                ],
                "learning_objectives": [
                    "Complete payment transaction",
                    "Ask about return policy",
                    "Request receipt",
                ],
                "success_criteria": [
                    "Complete payment",
                    "Understand return policy",
                    "Receive receipt",
                ],
                "cultural_notes": "Always keep receipts for returns; policies vary by store",
            },
        ],
    },
    "template_business_meeting": {
        "template_id": "template_business_meeting",
        "title": "Business Meeting",
        "description": "Participate in a professional business meeting",
        "category": "business",
        "difficulty": "advanced",
        "estimated_duration": 25,
        "language": "en",
        "user_role": "meeting participant",
        "ai_role": "colleague/manager",
        "setting": "Office conference room",
        "prerequisites": [
            "professional_vocabulary",
            "formal_expressions",
            "presentations",
        ],
        "learning_outcomes": [
            "Participate in business discussions",
            "Present ideas professionally",
            "Negotiate and compromise",
            "Use formal business language",
        ],
        "vocabulary_focus": [
            "agenda",
            "proposal",
            "deadline",
            "budget",
            "stakeholder",
            "deliverable",
            "milestone",
            "strategy",
            "objective",
            "action item",
        ],
        "cultural_context": {
            "punctuality": "Being on time is crucial in business",
            "hierarchy": "Respect organizational hierarchy",
            "communication": "Direct but polite communication is valued",
        },
        "phases": [
            {
                "name": "Meeting Opening",
                "description": "Start the meeting with introductions and agenda",
                "expected_duration_minutes": 5,
                "key_vocabulary": [
                    "agenda",
                    "minutes",
                    "objectives",
                    "attendees",
                    "timeframe",
                ],
                "essential_phrases": [
                    "Let's get started",
                    "Today's agenda includes...",
                    "Our objective is to...",
                    "Does anyone have questions before we begin?",
                ],
                "learning_objectives": [
                    "Understand meeting structure",
                    "Follow agenda items",
                    "Ask clarifying questions",
                ],
                "success_criteria": [
                    "Understand meeting objectives",
                    "Follow agenda progression",
                    "Ask at least one question",
                ],
                "cultural_notes": "Meetings typically start with agenda review; mobile phones should be silenced",
            },
            {
                "name": "Discussion and Collaboration",
                "description": "Participate in meeting discussions",
                "expected_duration_minutes": 10,
                "key_vocabulary": [
                    "point of view",
                    "suggestion",
                    "concern",
                    "agreement",
                    "alternative",
                    "pros and cons",
                ],
                "essential_phrases": [
                    "I'd like to add that...",
                    "From my perspective...",
                    "I have a concern about...",
                    "I agree/disagree because...",
                ],
                "learning_objectives": [
                    "Express opinions professionally",
                    "Agree or disagree politely",
                    "Build on others' ideas",
                ],
                "success_criteria": [
                    "Contribute to discussion",
                    "Express viewpoint clearly",
                    "Respond to others' points",
                ],
                "cultural_notes": "Wait for appropriate moments to speak; don't interrupt",
            },
            {
                "name": "Decision Making",
                "description": "Reach consensus and make decisions",
                "expected_duration_minutes": 7,
                "key_vocabulary": [
                    "consensus",
                    "vote",
                    "decision",
                    "next steps",
                    "responsibilities",
                    "timeline",
                ],
                "essential_phrases": [
                    "Can we reach a consensus on...?",
                    "Let's put this to a vote",
                    "Who will be responsible for...?",
                    "What's our timeline?",
                ],
                "learning_objectives": [
                    "Participate in decision-making",
                    "Understand assigned tasks",
                    "Clarify responsibilities",
                ],
                "success_criteria": [
                    "Contribute to decision",
                    "Understand action items",
                    "Note assigned responsibilities",
                ],
                "cultural_notes": "Decisions should be clear; ensure everyone understands their role",
            },
            {
                "name": "Meeting Wrap-up",
                "description": "Summarize and assign action items",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "summary",
                    "action items",
                    "follow-up",
                    "next meeting",
                    "deadlines",
                ],
                "essential_phrases": [
                    "To summarize...",
                    "Action items are...",
                    "When is the deadline?",
                    "I'll send out the meeting minutes",
                ],
                "learning_objectives": [
                    "Understand meeting outcomes",
                    "Note action items",
                    "Confirm deadlines",
                ],
                "success_criteria": [
                    "List your action items",
                    "Confirm deadlines",
                    "Understand next steps",
                ],
                "cultural_notes": "Meeting minutes are typically distributed afterward; review them carefully",
            },
        ],
    },
    "template_social_party": {
        "template_id": "template_social_party",
        "title": "Social Gathering",
        "description": "Navigate a social party or informal gathering",
        "category": "social",
        "difficulty": "intermediate",
        "estimated_duration": 15,
        "language": "en",
        "user_role": "party guest",
        "ai_role": "host/other guests",
        "setting": "House party or social event",
        "prerequisites": ["small_talk", "introductions", "common_topics"],
        "learning_outcomes": [
            "Make small talk",
            "Introduce yourself and others",
            "Navigate social situations",
            "Express interest in conversations",
        ],
        "vocabulary_focus": [
            "introduce",
            "mingle",
            "chat",
            "host",
            "guest",
            "snacks",
            "drinks",
            "music",
            "atmosphere",
            "fun",
        ],
        "cultural_context": {
            "punctuality": "Arriving 15-30 min late is acceptable for parties",
            "gifts": "Bringing a small gift for the host is polite",
            "mingling": "Expected to talk to multiple people",
        },
        "phases": [
            {
                "name": "Arrival and Greetings",
                "description": "Arrive at the party and greet the host",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "welcome",
                    "thank you for inviting",
                    "gift",
                    "coat",
                    "introduce",
                ],
                "essential_phrases": [
                    "Thank you for having me",
                    "This is for you",
                    "Your home is lovely",
                    "Where should I put my coat?",
                ],
                "learning_objectives": [
                    "Greet host appropriately",
                    "Give compliments",
                    "Ask practical questions",
                ],
                "success_criteria": [
                    "Thank the host",
                    "Give a compliment",
                    "Ask where to put belongings",
                ],
                "cultural_notes": "Bring wine, flowers, or dessert as a host gift",
            },
            {
                "name": "Making Small Talk",
                "description": "Engage in casual conversation with other guests",
                "expected_duration_minutes": 6,
                "key_vocabulary": [
                    "work",
                    "hobbies",
                    "weather",
                    "recent events",
                    "weekend plans",
                ],
                "essential_phrases": [
                    "How do you know the host?",
                    "What do you do?",
                    "Have you tried the food?",
                    "This music is great!",
                ],
                "learning_objectives": [
                    "Start conversations",
                    "Find common interests",
                    "Keep conversations flowing",
                ],
                "success_criteria": [
                    "Start conversation with stranger",
                    "Find common ground",
                    "Ask follow-up questions",
                ],
                "cultural_notes": "Avoid controversial topics like politics or religion in casual settings",
            },
            {
                "name": "Introducing People",
                "description": "Introduce yourself and others",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "meet",
                    "colleague",
                    "friend",
                    "neighbor",
                    "this is",
                ],
                "essential_phrases": [
                    "I'd like you to meet...",
                    "Have you two met?",
                    "This is my friend/colleague...",
                    "Nice to meet you",
                ],
                "learning_objectives": [
                    "Introduce yourself",
                    "Introduce others",
                    "Remember names",
                ],
                "success_criteria": [
                    "Introduce yourself properly",
                    "Introduce two people",
                    "Use people's names in conversation",
                ],
                "cultural_notes": "It's polite to introduce people who haven't met",
            },
            {
                "name": "Departure",
                "description": "Say goodbye and thank the host",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "leaving",
                    "wonderful time",
                    "thank you",
                    "goodbye",
                    "see you soon",
                ],
                "essential_phrases": [
                    "I should get going",
                    "Thank you so much for having me",
                    "I had a wonderful time",
                    "Let's keep in touch",
                ],
                "learning_objectives": [
                    "Leave gracefully",
                    "Express gratitude",
                    "Exchange contact information",
                ],
                "success_criteria": [
                    "Find host to say goodbye",
                    "Thank the host",
                    "Exchange contacts with someone",
                ],
                "cultural_notes": "Always find the host to say goodbye; don't just slip away",
            },
        ],
    },
    "template_healthcare_appointment": {
        "template_id": "template_healthcare_appointment",
        "title": "Doctor's Appointment",
        "description": "Visit a doctor and describe symptoms",
        "category": "healthcare",
        "difficulty": "intermediate",
        "estimated_duration": 20,
        "language": "en",
        "user_role": "patient",
        "ai_role": "doctor/nurse",
        "setting": "Medical clinic or doctor's office",
        "prerequisites": ["body_parts", "symptoms", "health_vocabulary"],
        "learning_outcomes": [
            "Describe symptoms accurately",
            "Answer medical questions",
            "Understand medical advice",
            "Discuss treatment options",
        ],
        "vocabulary_focus": [
            "symptoms",
            "pain",
            "fever",
            "medication",
            "prescription",
            "allergy",
            "insurance",
            "appointment",
            "examination",
            "diagnosis",
        ],
        "cultural_context": {
            "privacy": "Medical information is confidential",
            "insurance": "Bring insurance card to appointments",
            "honesty": "Be honest about all symptoms and medications",
        },
        "phases": [
            {
                "name": "Check-in and Registration",
                "description": "Check in at reception and provide information",
                "expected_duration_minutes": 4,
                "key_vocabulary": [
                    "appointment",
                    "insurance",
                    "forms",
                    "copay",
                    "wait",
                ],
                "essential_phrases": [
                    "I have an appointment with Dr...",
                    "Here's my insurance card",
                    "How long is the wait?",
                    "I need to update my information",
                ],
                "learning_objectives": [
                    "Check in properly",
                    "Provide insurance information",
                    "Complete forms",
                ],
                "success_criteria": [
                    "Confirm appointment",
                    "Provide required documents",
                    "Ask about wait time",
                ],
                "cultural_notes": "Arrive 10-15 minutes early for paperwork",
            },
            {
                "name": "Describing Symptoms",
                "description": "Explain your health concerns to the doctor",
                "expected_duration_minutes": 7,
                "key_vocabulary": [
                    "ache",
                    "pain",
                    "dizzy",
                    "nausea",
                    "cough",
                    "fever",
                    "fatigue",
                    "since when",
                    "how often",
                ],
                "essential_phrases": [
                    "I've been feeling...",
                    "It started... days ago",
                    "The pain is in my...",
                    "It hurts when I...",
                ],
                "learning_objectives": [
                    "Describe symptoms clearly",
                    "Answer medical history questions",
                    "Explain duration and severity",
                ],
                "success_criteria": [
                    "Describe main symptoms",
                    "Explain when symptoms started",
                    "Answer doctor's questions",
                ],
                "cultural_notes": "Be specific about symptoms; doctors need details to diagnose",
            },
            {
                "name": "Examination and Questions",
                "description": "Undergo examination and answer questions",
                "expected_duration_minutes": 5,
                "key_vocabulary": [
                    "blood pressure",
                    "temperature",
                    "heart rate",
                    "examine",
                    "allergies",
                    "medications",
                ],
                "essential_phrases": [
                    "I'm allergic to...",
                    "I'm currently taking...",
                    "Does this hurt?",
                    "Can you explain what you're doing?",
                ],
                "learning_objectives": [
                    "Understand examination procedures",
                    "Provide medical history",
                    "Ask clarifying questions",
                ],
                "success_criteria": [
                    "Cooperate with examination",
                    "Disclose allergies and medications",
                    "Ask about procedures",
                ],
                "cultural_notes": "Always tell doctor about all medications, including supplements",
            },
            {
                "name": "Diagnosis and Treatment",
                "description": "Understand diagnosis and treatment plan",
                "expected_duration_minutes": 4,
                "key_vocabulary": [
                    "diagnosis",
                    "treatment",
                    "prescription",
                    "rest",
                    "follow-up",
                    "recovery",
                    "side effects",
                ],
                "essential_phrases": [
                    "What's the diagnosis?",
                    "What should I do?",
                    "How should I take this medication?",
                    "When should I come back?",
                ],
                "learning_objectives": [
                    "Understand diagnosis",
                    "Follow medication instructions",
                    "Know when to return",
                ],
                "success_criteria": [
                    "Understand diagnosis",
                    "Get prescription instructions",
                    "Schedule follow-up if needed",
                ],
                "cultural_notes": "Don't hesitate to ask doctor to repeat or clarify; your health is important",
            },
        ],
    },
    "template_emergency_situation": {
        "template_id": "template_emergency_situation",
        "title": "Emergency Situation",
        "description": "Handle an emergency and call for help",
        "category": "emergency",
        "difficulty": "intermediate",
        "estimated_duration": 10,
        "language": "en",
        "user_role": "person in need/caller",
        "ai_role": "emergency operator/helper",
        "setting": "Emergency situation requiring assistance",
        "prerequisites": ["basic_vocabulary", "numbers", "locations"],
        "learning_outcomes": [
            "Call for emergency help",
            "Describe emergency situations",
            "Provide location information",
            "Stay calm under pressure",
        ],
        "vocabulary_focus": [
            "emergency",
            "help",
            "ambulance",
            "police",
            "fire",
            "injured",
            "accident",
            "address",
            "urgent",
            "911/112",
        ],
        "cultural_context": {
            "emergency_number": "911 in US/Canada, 112 in Europe, 999 in UK",
            "stay_calm": "Operators are trained to help you",
            "don't_hang_up": "Stay on the line until help arrives",
        },
        "phases": [
            {
                "name": "Recognizing the Emergency",
                "description": "Identify that an emergency is occurring",
                "expected_duration_minutes": 2,
                "key_vocabulary": [
                    "emergency",
                    "help",
                    "urgent",
                    "danger",
                    "immediate",
                ],
                "essential_phrases": [
                    "I need help!",
                    "Call 911!",
                    "This is an emergency",
                    "Someone is hurt",
                ],
                "learning_objectives": [
                    "Recognize emergency situations",
                    "Call for help immediately",
                    "Alert others nearby",
                ],
                "success_criteria": [
                    "Identify emergency",
                    "Call emergency number",
                    "Alert others if possible",
                ],
                "cultural_notes": "Don't hesitate to call emergency services if you're unsure",
            },
            {
                "name": "Speaking with Emergency Operator",
                "description": "Provide critical information to operator",
                "expected_duration_minutes": 4,
                "key_vocabulary": [
                    "location",
                    "address",
                    "landmarks",
                    "injuries",
                    "breathing",
                    "conscious",
                    "bleeding",
                ],
                "essential_phrases": [
                    "I'm at...",
                    "The address is...",
                    "Someone is injured",
                    "They're not breathing",
                ],
                "learning_objectives": [
                    "Provide clear location",
                    "Describe situation accurately",
                    "Answer operator's questions",
                ],
                "success_criteria": [
                    "Give exact location",
                    "Describe emergency clearly",
                    "Follow operator's instructions",
                ],
                "cultural_notes": "Operators will ask specific questions; answer as best you can",
            },
            {
                "name": "Following Instructions",
                "description": "Follow operator's guidance until help arrives",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "instructions",
                    "wait",
                    "stay",
                    "don't move",
                    "pressure",
                    "CPR",
                    "breathing",
                ],
                "essential_phrases": [
                    "What should I do?",
                    "Should I move them?",
                    "Help is on the way",
                    "Stay with me",
                ],
                "learning_objectives": [
                    "Follow medical instructions",
                    "Keep person comfortable",
                    "Update operator on changes",
                ],
                "success_criteria": [
                    "Follow all instructions",
                    "Stay on the line",
                    "Report any changes",
                ],
                "cultural_notes": "Operator may guide you through first aid; listen carefully",
            },
            {
                "name": "Help Arrival",
                "description": "Assist emergency responders when they arrive",
                "expected_duration_minutes": 1,
                "key_vocabulary": [
                    "paramedics",
                    "ambulance",
                    "police",
                    "what happened",
                    "medical history",
                    "medications",
                ],
                "essential_phrases": [
                    "Over here!",
                    "This is what happened...",
                    "They take these medications",
                    "Thank you for coming",
                ],
                "learning_objectives": [
                    "Guide responders to scene",
                    "Provide relevant information",
                    "Step back when instructed",
                ],
                "success_criteria": [
                    "Flag down emergency vehicles",
                    "Brief responders quickly",
                    "Provide medical information if known",
                ],
                "cultural_notes": "Give responders space to work; they'll ask if they need more information",
            },
        ],
    },
    "template_daily_life_bank": {
        "template_id": "template_daily_life_bank",
        "title": "Banking Transaction",
        "description": "Perform common banking tasks at a bank branch",
        "category": "daily_life",
        "difficulty": "beginner",
        "estimated_duration": 15,
        "language": "en",
        "user_role": "customer",
        "ai_role": "bank teller",
        "setting": "Bank branch",
        "prerequisites": ["numbers", "basic_finance_terms", "identification"],
        "learning_outcomes": [
            "Open a bank account",
            "Make deposits and withdrawals",
            "Ask about banking services",
            "Understand banking terminology",
        ],
        "vocabulary_focus": [
            "account",
            "deposit",
            "withdraw",
            "balance",
            "transfer",
            "savings",
            "checking",
            "ATM",
            "PIN",
            "statement",
        ],
        "cultural_context": {
            "ID_required": "Bring government-issued ID for transactions",
            "privacy": "Keep PIN private; don't share with anyone",
            "fees": "Ask about account fees and minimum balance",
        },
        "phases": [
            {
                "name": "Entering and Waiting",
                "description": "Enter bank and wait for service",
                "expected_duration_minutes": 2,
                "key_vocabulary": ["teller", "line", "queue", "wait", "next"],
                "essential_phrases": [
                    "Where's the line?",
                    "How long is the wait?",
                    "Next, please",
                    "I'd like to see a teller",
                ],
                "learning_objectives": [
                    "Navigate bank layout",
                    "Understand queuing system",
                    "Wait for service",
                ],
                "success_criteria": [
                    "Find correct line",
                    "Wait patiently",
                    "Approach when called",
                ],
                "cultural_notes": "Take a number if there's a ticket system; wait for your turn",
            },
            {
                "name": "Stating Your Needs",
                "description": "Explain what service you need",
                "expected_duration_minutes": 5,
                "key_vocabulary": [
                    "deposit",
                    "withdrawal",
                    "cash",
                    "check",
                    "account number",
                ],
                "essential_phrases": [
                    "I'd like to deposit...",
                    "I need to withdraw...",
                    "Can I cash this check?",
                    "I want to transfer money",
                ],
                "learning_objectives": [
                    "Explain banking needs",
                    "Provide account information",
                    "Complete transaction forms",
                ],
                "success_criteria": [
                    "State transaction type",
                    "Provide ID when asked",
                    "Fill out required slips",
                ],
                "cultural_notes": "Have your account number and ID ready",
            },
            {
                "name": "Transaction Processing",
                "description": "Complete the transaction",
                "expected_duration_minutes": 5,
                "key_vocabulary": [
                    "verify",
                    "sign",
                    "receipt",
                    "confirmation",
                    "amount",
                ],
                "essential_phrases": [
                    "Is this correct?",
                    "Where do I sign?",
                    "Can I get a receipt?",
                    "What's my new balance?",
                ],
                "learning_objectives": [
                    "Verify transaction details",
                    "Sign documents correctly",
                    "Get confirmation",
                ],
                "success_criteria": [
                    "Verify amount is correct",
                    "Sign where indicated",
                    "Receive receipt",
                ],
                "cultural_notes": "Always verify amounts before signing; keep receipts",
            },
            {
                "name": "Additional Services",
                "description": "Ask about other banking services",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "interest rate",
                    "fees",
                    "online banking",
                    "app",
                    "credit card",
                    "loan",
                ],
                "essential_phrases": [
                    "What services do you offer?",
                    "How do I set up online banking?",
                    "Are there any fees?",
                    "What's the interest rate?",
                ],
                "learning_objectives": [
                    "Ask about banking products",
                    "Understand fee structure",
                    "Learn about digital services",
                ],
                "success_criteria": [
                    "Ask about one service",
                    "Understand basic fees",
                    "Get information brochure",
                ],
                "cultural_notes": "Banks offer various services; don't hesitate to ask questions",
            },
        ],
    },
    "template_hobbies_sports": {
        "template_id": "template_hobbies_sports",
        "title": "Joining a Sports Class",
        "description": "Sign up for and participate in a sports or fitness class",
        "category": "hobbies",
        "difficulty": "beginner",
        "estimated_duration": 15,
        "language": "en",
        "user_role": "student/participant",
        "ai_role": "instructor/staff",
        "setting": "Gym or sports facility",
        "prerequisites": ["sports_vocabulary", "body_movements", "basic_instructions"],
        "learning_outcomes": [
            "Join a sports class",
            "Follow exercise instructions",
            "Ask about technique",
            "Discuss fitness goals",
        ],
        "vocabulary_focus": [
            "warm-up",
            "exercise",
            "repetition",
            "set",
            "stretch",
            "technique",
            "form",
            "equipment",
            "membership",
            "schedule",
        ],
        "cultural_context": {
            "attire": "Wear appropriate athletic clothing",
            "punctuality": "Arrive 5-10 minutes early",
            "hygiene": "Wipe down equipment after use",
        },
        "phases": [
            {
                "name": "Registration and Tour",
                "description": "Sign up for class and tour the facility",
                "expected_duration_minutes": 5,
                "key_vocabulary": [
                    "membership",
                    "class schedule",
                    "locker room",
                    "equipment",
                    "facilities",
                ],
                "essential_phrases": [
                    "I'm interested in joining",
                    "What classes do you offer?",
                    "Can I try a class first?",
                    "Where are the locker rooms?",
                ],
                "learning_objectives": [
                    "Inquire about classes",
                    "Understand membership options",
                    "Navigate facility",
                ],
                "success_criteria": [
                    "Ask about class types",
                    "Understand pricing",
                    "Locate changing areas",
                ],
                "cultural_notes": "Many gyms offer trial classes; ask about it",
            },
            {
                "name": "Class Introduction",
                "description": "Meet instructor and classmates",
                "expected_duration_minutes": 3,
                "key_vocabulary": [
                    "beginner",
                    "experience level",
                    "fitness goals",
                    "injuries",
                    "modifications",
                ],
                "essential_phrases": [
                    "I'm a beginner",
                    "I have a knee injury",
                    "What if I can't keep up?",
                    "Can you show me modifications?",
                ],
                "learning_objectives": [
                    "Introduce yourself",
                    "Disclose fitness level",
                    "Ask about modifications",
                ],
                "success_criteria": [
                    "Tell instructor your level",
                    "Mention any injuries",
                    "Ask at least one question",
                ],
                "cultural_notes": "Always tell instructor about injuries beforehand",
            },
            {
                "name": "Participating in Class",
                "description": "Follow along with exercises",
                "expected_duration_minutes": 5,
                "key_vocabulary": [
                    "inhale",
                    "exhale",
                    "hold",
                    "repeat",
                    "faster",
                    "slower",
                    "left",
                    "right",
                    "up",
                    "down",
                ],
                "essential_phrases": [
                    "Like this?",
                    "Am I doing this right?",
                    "I need a break",
                    "Can you slow down?",
                ],
                "learning_objectives": [
                    "Follow verbal instructions",
                    "Ask for technique help",
                    "Know when to rest",
                ],
                "success_criteria": [
                    "Follow basic movements",
                    "Ask about technique",
                    "Take breaks when needed",
                ],
                "cultural_notes": "It's okay to take breaks; go at your own pace",
            },
            {
                "name": "Cool Down and Feedback",
                "description": "Finish class and discuss progress",
                "expected_duration_minutes": 2,
                "key_vocabulary": [
                    "stretch",
                    "cool down",
                    "sore",
                    "progress",
                    "next class",
                ],
                "essential_phrases": [
                    "That was great!",
                    "When's the next class?",
                    "I'll be sore tomorrow",
                    "Thanks for the tips",
                ],
                "learning_objectives": [
                    "Complete cool-down",
                    "Thank instructor",
                    "Plan next session",
                ],
                "success_criteria": [
                    "Complete stretching",
                    "Ask about next class",
                    "Thank instructor",
                ],
                "cultural_notes": "Stretching after exercise is important; don't skip it",
            },
        ],
    },
    "template_education_library": {
        "template_id": "template_education_library",
        "title": "Using the Library",
        "description": "Navigate a library, find resources, and check out materials",
        "category": "education",
        "difficulty": "beginner",
        "estimated_duration": 15,
        "language": "en",
        "user_role": "library patron",
        "ai_role": "librarian",
        "setting": "Public or university library",
        "prerequisites": ["basic_reading", "categories", "asking_directions"],
        "learning_outcomes": [
            "Get a library card",
            "Find books and resources",
            "Use library catalog system",
            "Check out materials",
        ],
        "vocabulary_focus": [
            "library card",
            "catalog",
            "checkout",
            "due date",
            "renew",
            "reference",
            "fiction",
            "non-fiction",
            "periodicals",
            "database",
        ],
        "cultural_context": {
            "quiet": "Libraries require quiet voices",
            "free": "Most library services are free",
            "returns": "Return books on time to avoid fines",
        },
        "phases": [
            {
                "name": "Getting a Library Card",
                "description": "Register for a library card",
                "expected_duration_minutes": 4,
                "key_vocabulary": [
                    "library card",
                    "register",
                    "ID",
                    "address",
                    "application",
                ],
                "essential_phrases": [
                    "I'd like to get a library card",
                    "What do I need to bring?",
                    "Is there a fee?",
                    "How long does it take?",
                ],
                "learning_objectives": [
                    "Understand registration process",
                    "Provide required documents",
                    "Complete application",
                ],
                "success_criteria": [
                    "Fill out application",
                    "Provide ID and proof of address",
                    "Receive library card",
                ],
                "cultural_notes": "Bring ID and proof of address (utility bill, lease)",
            },
            {
                "name": "Finding Resources",
                "description": "Search for and locate books or materials",
                "expected_duration_minutes": 5,
                "key_vocabulary": [
                    "catalog",
                    "search",
                    "call number",
                    "section",
                    "shelf",
                    "floor",
                ],
                "essential_phrases": [
                    "I'm looking for...",
                    "How do I find books on...?",
                    "Where is the fiction section?",
                    "Can you help me find this?",
                ],
                "learning_objectives": [
                    "Use library catalog",
                    "Understand call numbers",
                    "Navigate library layout",
                ],
                "success_criteria": [
                    "Search catalog successfully",
                    "Locate correct section",
                    "Find at least one item",
                ],
                "cultural_notes": "Librarians are there to help; don't hesitate to ask",
            },
            {
                "name": "Checking Out Materials",
                "description": "Check out books and understand policies",
                "expected_duration_minutes": 4,
                "key_vocabulary": [
                    "checkout",
                    "borrow",
                    "due date",
                    "limit",
                    "renew",
                    "hold",
                ],
                "essential_phrases": [
                    "I'd like to check these out",
                    "When are these due?",
                    "How many can I borrow?",
                    "Can I renew online?",
                ],
                "learning_objectives": [
                    "Complete checkout process",
                    "Understand loan periods",
                    "Learn renewal procedures",
                ],
                "success_criteria": [
                    "Check out materials",
                    "Note due dates",
                    "Understand renewal process",
                ],
                "cultural_notes": "Most libraries allow online renewals; sign up for email reminders",
            },
            {
                "name": "Additional Services",
                "description": "Learn about other library services",
                "expected_duration_minutes": 2,
                "key_vocabulary": [
                    "computer access",
                    "printing",
                    "study room",
                    "events",
                    "digital library",
                    "e-books",
                ],
                "essential_phrases": [
                    "Do you have computers?",
                    "Can I print here?",
                    "Are there study rooms?",
                    "What programs do you offer?",
                ],
                "learning_objectives": [
                    "Discover available services",
                    "Understand computer access",
                    "Learn about programs",
                ],
                "success_criteria": [
                    "Ask about one service",
                    "Understand computer policy",
                    "Take events calendar",
                ],
                "cultural_notes": "Libraries offer many free services: computers, WiFi, classes, events",
            },
        ],
    },
}


def get_all_templates() -> List[Dict]:
    """Get all scenario templates as a list"""
    return list(SCENARIO_TEMPLATES.values())


def get_template_by_id(template_id: str) -> Optional[Dict]:
    """Get a specific template by ID"""
    return SCENARIO_TEMPLATES.get(template_id)


def get_templates_by_category(category: str) -> List[Dict]:
    """Get templates filtered by category"""
    return [
        template
        for template in SCENARIO_TEMPLATES.values()
        if template["category"] == category
    ]


def get_template_categories() -> List[str]:
    """Get list of all available template categories"""
    return list(set(template["category"] for template in SCENARIO_TEMPLATES.values()))


class ScenarioTemplates:
    """Factory methods for creating UniversalScenarioTemplate instances"""

    @staticmethod
    def create_greetings_template() -> UniversalScenarioTemplate:
        """Create greetings and introductions template"""
        return UniversalScenarioTemplate(
            template_id="greetings_introductions",
            name="Greetings and Introductions",
            category=ScenarioCategory.SOCIAL,
            tier=1,
            base_vocabulary=[
                "hello",
                "hi",
                "good morning",
                "good afternoon",
                "good evening",
                "goodbye",
                "see you later",
                "nice to meet you",
                "my name is",
                "what's your name",
                "how are you",
                "I'm fine",
                "thank you",
                "please",
                "excuse me",
                "sorry",
                "where are you from",
                "I'm from",
                "how old are you",
                "occupation",
                "student",
                "work",
            ],
            essential_phrases={
                "beginner": [
                    "Hello, my name is...",
                    "Nice to meet you",
                    "How are you?",
                    "I'm fine, thank you",
                    "Where are you from?",
                    "I'm from...",
                ],
                "intermediate": [
                    "It's a pleasure to meet you",
                    "How has your day been?",
                    "What do you do for work?",
                    "I work as a...",
                    "How long have you been here?",
                    "What brings you here?",
                ],
                "advanced": [
                    "I'd like to introduce myself",
                    "May I ask what you do professionally?",
                    "I've heard so much about this place",
                    "What's your impression of...?",
                    "How do you find living here?",
                    "It's been wonderful meeting you",
                ],
            },
            cultural_context={
                "notes": "Greeting customs vary by culture. Some prefer formal titles, others are more casual. Physical contact (handshakes, cheek kisses) varies by region.",
                "formality_levels": ["very_formal", "formal", "casual", "informal"],
                "time_sensitivity": "morning/afternoon/evening greetings",
                "regional_variations": True,
            },
            learning_objectives=[
                "Master basic greeting expressions",
                "Learn to introduce yourself confidently",
                "Practice asking and answering personal questions",
                "Understand cultural greeting norms",
                "Build confidence in first conversations",
            ],
            conversation_starters=[
                "Hello! I don't think we've met.",
                "Good morning! How are you today?",
                "Hi there! Are you new here?",
                "Excuse me, could you help me with something?",
                "I'm sorry, but do I know you from somewhere?",
            ],
            scenario_variations=[
                {
                    "id": "formal_meeting",
                    "description": "Formal introduction at business or academic setting",
                    "setting": "Professional conference or business meeting",
                    "phases": [
                        "formal_greeting",
                        "title_exchange",
                        "business_cards",
                        "small_talk",
                        "polite_departure",
                    ],
                },
                {
                    "id": "casual_meeting",
                    "description": "Casual introduction at social gathering",
                    "setting": "Party, coffee shop, or social event",
                    "phases": [
                        "casual_greeting",
                        "name_exchange",
                        "background_sharing",
                        "interest_discussion",
                        "contact_exchange",
                    ],
                },
                {
                    "id": "neighbor_meeting",
                    "description": "Meeting a new neighbor",
                    "setting": "Apartment building, neighborhood, local area",
                    "phases": [
                        "neighborly_greeting",
                        "location_discussion",
                        "local_recommendations",
                        "future_contact",
                    ],
                },
            ],
            difficulty_modifiers={
                "beginner": {
                    "duration": 10,
                    "phase_duration": 3,
                    "vocab_limit": 15,
                    "prerequisites": [],
                },
                "intermediate": {
                    "duration": 15,
                    "phase_duration": 4,
                    "vocab_limit": 20,
                    "prerequisites": ["basic_vocabulary", "simple_questions"],
                },
                "advanced": {
                    "duration": 20,
                    "phase_duration": 5,
                    "vocab_limit": 25,
                    "prerequisites": [
                        "intermediate_conversation",
                        "cultural_awareness",
                    ],
                },
            },
            success_metrics=[
                "Successfully exchange names",
                "Ask and answer 3 personal questions",
                "Use appropriate greeting for time/context",
                "Maintain natural conversation flow",
                "End conversation politely",
            ],
        )

    @staticmethod

    @staticmethod
    def create_daily_routine_template() -> UniversalScenarioTemplate:
        """Create daily routine template"""
        return UniversalScenarioTemplate(
            template_id="daily_routine",
            name="Daily Routine",
            category=ScenarioCategory.DAILY_LIFE,
            tier=2,
            base_vocabulary=[
                "morning",
                "afternoon",
                "evening",
                "night",
                "wake up",
                "get up",
                "brush teeth",
                "shower",
                "breakfast",
                "lunch",
                "dinner",
                "work",
                "school",
                "sleep",
                "exercise",
                "hobby",
                "schedule",
                "time",
                "early",
                "late",
                "busy",
                "free time",
                "weekend",
                "weekday",
            ],
            essential_phrases={
                "beginner": [
                    "I wake up at...",
                    "I go to work",
                    "I have breakfast",
                    "What time do you...?",
                ],
                "intermediate": [
                    "My daily routine is...",
                    "I usually start my day with...",
                    "In the evening, I like to...",
                ],
                "advanced": [
                    "I'm trying to establish a better routine",
                    "My schedule varies depending on...",
                ],
            },
            cultural_context={
                "notes": "Daily routines vary significantly across cultures and lifestyles"
            },
            learning_objectives=[
                "Describe daily activities",
                "Talk about time and schedules",
                "Express habits and routines",
            ],
            conversation_starters=[
                "What's your typical day like?",
                "When do you usually wake up?",
            ],
            scenario_variations=[
                {
                    "id": "workday",
                    "description": "Typical working day routine",
                    "phases": [
                        "morning_routine",
                        "work_preparation",
                        "work_day",
                        "evening_activities",
                    ],
                },
                {
                    "id": "weekend",
                    "description": "Weekend routine discussion",
                    "phases": [
                        "weekend_morning",
                        "leisure_activities",
                        "social_time",
                        "relaxation",
                    ],
                },
            ],
            difficulty_modifiers={
                "beginner": {"duration": 10},
                "intermediate": {"duration": 15},
                "advanced": {"duration": 20},
            },
            success_metrics=[
                "Describe complete daily routine",
                "Use time expressions correctly",
                "Express preferences about activities",
            ],
        )

    @staticmethod

    @staticmethod
    def create_basic_conversations_template() -> UniversalScenarioTemplate:
        """Create basic conversations template"""
        return UniversalScenarioTemplate(
            template_id="basic_conversations",
            name="Basic Conversations",
            category=ScenarioCategory.SOCIAL,
            tier=2,
            base_vocabulary=[
                "yes",
                "no",
                "maybe",
                "please",
                "thank you",
                "sorry",
                "excuse me",
                "help",
                "understand",
                "speak",
                "listen",
                "repeat",
                "slow",
                "fast",
                "question",
                "answer",
                "problem",
                "solution",
                "agree",
                "disagree",
            ],
            essential_phrases={
                "beginner": [
                    "Can you help me?",
                    "I don't understand",
                    "Could you repeat that?",
                    "Thank you very much",
                ],
                "intermediate": [
                    "Could you speak more slowly?",
                    "What does that mean?",
                    "I'm not sure I follow",
                ],
                "advanced": [
                    "I beg your pardon?",
                    "Could you clarify what you mean by...?",
                    "I'm afraid I didn't catch that",
                ],
            },
            cultural_context={
                "notes": "Politeness levels and conversation patterns vary by culture"
            },
            learning_objectives=[
                "Master essential conversation phrases",
                "Learn to ask for clarification",
                "Practice polite interruptions",
            ],
            conversation_starters=[
                "Excuse me, could you help me?",
                "I have a question",
                "Sorry to bother you",
            ],
            scenario_variations=[
                {
                    "id": "asking_help",
                    "description": "Asking for help or assistance",
                    "phases": [
                        "polite_approach",
                        "explain_need",
                        "receive_help",
                        "thank_and_close",
                    ],
                },
                {
                    "id": "clarification",
                    "description": "Asking for clarification",
                    "phases": [
                        "indicate_confusion",
                        "request_explanation",
                        "confirm_understanding",
                        "continue_conversation",
                    ],
                },
            ],
            difficulty_modifiers={
                "beginner": {"duration": 8},
                "intermediate": {"duration": 12},
                "advanced": {"duration": 15},
            },
            success_metrics=[
                "Use polite expressions correctly",
                "Ask for help appropriately",
                "Handle misunderstandings gracefully",
            ],
        )

    @staticmethod

    @staticmethod
    def create_family_template() -> UniversalScenarioTemplate:
        """Create family and relationships template"""
        return UniversalScenarioTemplate(
            template_id="family_relationships",
            name="Family and Relationships",
            category=ScenarioCategory.SOCIAL,
            tier=1,
            base_vocabulary=[
                "family",
                "mother",
                "father",
                "parents",
                "sister",
                "brother",
                "grandmother",
                "grandfather",
                "aunt",
                "uncle",
                "cousin",
                "husband",
                "wife",
                "son",
                "daughter",
                "children",
                "baby",
                "married",
                "single",
                "divorced",
                "relationship",
                "love",
                "close",
                "live with",
                "visit",
                "call",
                "text",
                "birthday",
            ],
            essential_phrases={
                "beginner": [
                    "I have a...",
                    "My family is...",
                    "Do you have children?",
                    "How many brothers and sisters?",
                    "My parents live in...",
                    "I live with...",
                ],
                "intermediate": [
                    "I'm very close to my...",
                    "We get together every...",
                    "My family means a lot to me",
                    "Do you see your family often?",
                    "We have family traditions",
                    "My relatives are scattered around...",
                ],
                "advanced": [
                    "Family dynamics can be complex",
                    "We maintain strong family bonds",
                    "There's always been tension between...",
                    "Family gatherings are important to us",
                    "We have different perspectives on...",
                    "Extended family plays a significant role",
                ],
            },
            cultural_context={
                "notes": "Family structures and relationships vary greatly across cultures. Some cultures emphasize extended family, others focus on nuclear family.",
                "family_values": [
                    "collectivist",
                    "individualist",
                    "hierarchical",
                    "egalitarian",
                ],
                "sensitive_topics": ["divorce", "childlessness", "family conflicts"],
                "celebration_customs": ["birthdays", "anniversaries", "reunions"],
            },
            learning_objectives=[
                "Describe family members and relationships",
                "Discuss family activities and traditions",
                "Express feelings about family",
                "Ask appropriate questions about family",
                "Understand cultural family differences",
            ],
            conversation_starters=[
                "Tell me about your family.",
                "Do you have any siblings?",
                "What's your family like?",
                "Are you close to your relatives?",
                "Do you have family traditions?",
            ],
            scenario_variations=[
                {
                    "id": "family_introduction",
                    "description": "Introducing family members to someone new",
                    "setting": "Social gathering where family meets friends",
                    "phases": [
                        "family_overview",
                        "individual_introductions",
                        "family_stories",
                        "shared_activities",
                    ],
                },
                {
                    "id": "family_discussion",
                    "description": "Casual conversation about family life",
                    "setting": "Coffee with a friend or colleague",
                    "phases": [
                        "family_updates",
                        "relationship_dynamics",
                        "family_challenges",
                        "family_celebrations",
                    ],
                },
            ],
            difficulty_modifiers={
                "beginner": {"duration": 12, "phase_duration": 4, "vocab_limit": 15},
                "intermediate": {
                    "duration": 18,
                    "phase_duration": 5,
                    "vocab_limit": 22,
                },
                "advanced": {"duration": 25, "phase_duration": 6, "vocab_limit": 26},
            },
            success_metrics=[
                "Accurately describe immediate family",
                "Use appropriate relationship vocabulary",
                "Share family story or tradition",
                "Ask follow-up questions about family",
                "Navigate sensitive topics appropriately",
            ],
        )

    @staticmethod

    @staticmethod
    def create_restaurant_template() -> UniversalScenarioTemplate:
        """Create restaurant and dining template"""
        return UniversalScenarioTemplate(
            template_id="restaurant_dining",
            name="Restaurant and Dining",
            category=ScenarioCategory.RESTAURANT,
            tier=1,
            base_vocabulary=[
                "restaurant",
                "menu",
                "waiter",
                "waitress",
                "table",
                "reservation",
                "order",
                "appetizer",
                "main course",
                "dessert",
                "drink",
                "beverage",
                "bill",
                "check",
                "tip",
                "payment",
                "credit card",
                "cash",
                "delicious",
                "tasty",
                "spicy",
                "mild",
                "vegetarian",
                "allergy",
            ],
            essential_phrases={
                "beginner": [
                    "Table for two, please",
                    "Can I see the menu?",
                    "I would like...",
                    "What do you recommend?",
                    "The check, please",
                    "How much is the tip?",
                ],
                "intermediate": [
                    "Do you have a table available?",
                    "What's the specialty of the house?",
                    "I'm allergic to...",
                    "Could you make that less spicy?",
                    "We're ready to order",
                    "Could we get separate checks?",
                ],
                "advanced": [
                    "We'd like to make a reservation",
                    "Could you describe this dish?",
                    "What wine would pair well with...?",
                    "Is this dish prepared with...?",
                    "We're celebrating a special occasion",
                    "The service has been excellent",
                ],
            },
            cultural_context={
                "notes": "Dining customs vary globally. Tipping practices, meal timing, and dining etiquette differ significantly between cultures.",
                "tipping_customs": ["included", "expected", "optional", "offensive"],
                "dining_styles": [
                    "family_style",
                    "individual_plates",
                    "buffet",
                    "course_by_course",
                ],
                "meal_times": ["early", "late", "multiple_seatings"],
            },
            learning_objectives=[
                "Navigate restaurant interactions confidently",
                "Order food and drinks appropriately",
                "Handle payment and tipping",
                "Express dietary restrictions and preferences",
                "Engage in pleasant dining conversation",
            ],
            conversation_starters=[
                "Have you been here before?",
                "What looks good to you?",
                "Excuse me, could we order?",
                "Is this your first time trying this cuisine?",
                "How's your meal?",
            ],
            scenario_variations=[
                {
                    "id": "casual_dining",
                    "description": "Casual restaurant or cafe experience",
                    "setting": "Local restaurant, cafe, or bistro",
                    "phases": [
                        "arrival_seating",
                        "menu_browsing",
                        "ordering",
                        "dining_conversation",
                        "payment_departure",
                    ],
                },
                {
                    "id": "fine_dining",
                    "description": "Upscale restaurant experience",
                    "setting": "High-end restaurant with formal service",
                    "phases": [
                        "reservation_arrival",
                        "wine_selection",
                        "course_ordering",
                        "dining_etiquette",
                        "appreciation_payment",
                    ],
                },
                {
                    "id": "fast_casual",
                    "description": "Quick service restaurant",
                    "setting": "Fast-casual chain or counter service",
                    "phases": [
                        "menu_decision",
                        "counter_ordering",
                        "payment",
                        "pickup_seating",
                        "quick_meal",
                    ],
                },
            ],
            difficulty_modifiers={
                "beginner": {"duration": 15, "phase_duration": 4, "vocab_limit": 15},
                "intermediate": {
                    "duration": 20,
                    "phase_duration": 5,
                    "vocab_limit": 20,
                },
                "advanced": {"duration": 25, "phase_duration": 6, "vocab_limit": 25},
            },
            success_metrics=[
                "Successfully place an order",
                "Handle dietary restrictions",
                "Calculate appropriate tip",
                "Engage in mealtime conversation",
                "Complete payment process",
            ],
        )

    @staticmethod

    @staticmethod
    def create_transportation_template() -> UniversalScenarioTemplate:
        """Create transportation template"""
        return UniversalScenarioTemplate(
            template_id="transportation",
            name="Transportation",
            category=ScenarioCategory.TRAVEL,
            tier=1,
            base_vocabulary=[
                "bus",
                "train",
                "subway",
                "taxi",
                "uber",
                "car",
                "bicycle",
                "airport",
                "station",
                "stop",
                "ticket",
                "fare",
                "schedule",
                "departure",
                "arrival",
                "platform",
                "gate",
                "seat",
                "luggage",
                "directions",
                "map",
                "GPS",
                "traffic",
                "delayed",
                "on time",
            ],
            essential_phrases={
                "beginner": [
                    "Where is the bus stop?",
                    "How much is the ticket?",
                    "When does the next train arrive?",
                    "I need to go to...",
                    "Is this the right platform?",
                    "Excuse me, is this seat taken?",
                ],
                "intermediate": [
                    "What's the best way to get to...?",
                    "How long does the journey take?",
                    "Do I need to transfer?",
                    "Is there a direct route?",
                    "What time does the last bus leave?",
                    "Can you call me a taxi?",
                ],
                "advanced": [
                    "Are there any delays on this route?",
                    "What's the most efficient route during rush hour?",
                    "Is there a monthly pass available?",
                    "Could you help me with the ticket machine?",
                    "What are the peak travel times?",
                    "Is there wheelchair accessibility?",
                ],
            },
            cultural_context={
                "notes": "Transportation systems vary greatly between cities and countries. Payment methods, etiquette, and accessibility differ.",
                "payment_methods": ["cash", "card", "mobile_app", "contactless"],
                "etiquette": ["quiet_zones", "priority_seating", "boarding_order"],
                "accessibility": ["wheelchair", "elderly", "pregnant", "disabled"],
            },
            learning_objectives=[
                "Navigate public transportation systems",
                "Purchase tickets and understand pricing",
                "Ask for and understand directions",
                "Handle transportation delays and changes",
                "Practice transportation-related vocabulary",
            ],
            conversation_starters=[
                "Excuse me, how do I get to...?",
                "Is this the right train for...?",
                "Do you know when the next bus comes?",
                "What's the best way to the airport?",
                "Have you used this app before?",
            ],
            scenario_variations=[
                {
                    "id": "public_transit",
                    "description": "Using buses, trains, or subway systems",
                    "setting": "Public transportation network",
                    "phases": [
                        "route_planning",
                        "ticket_purchase",
                        "boarding",
                        "journey",
                        "arrival_exit",
                    ],
                },
                {
                    "id": "ride_sharing",
                    "description": "Using taxi, Uber, or similar services",
                    "setting": "City streets and ride-sharing apps",
                    "phases": [
                        "booking_request",
                        "driver_communication",
                        "pickup",
                        "journey_conversation",
                        "payment_rating",
                    ],
                },
                {
                    "id": "airport_travel",
                    "description": "Navigating airport transportation",
                    "setting": "Airport and surrounding transport hubs",
                    "phases": [
                        "transport_selection",
                        "luggage_handling",
                        "check_in_process",
                        "security_navigation",
                        "gate_finding",
                    ],
                },
            ],
            difficulty_modifiers={
                "beginner": {"duration": 12, "phase_duration": 3, "vocab_limit": 15},
                "intermediate": {
                    "duration": 18,
                    "phase_duration": 4,
                    "vocab_limit": 20,
                },
                "advanced": {"duration": 22, "phase_duration": 5, "vocab_limit": 25},
            },
            success_metrics=[
                "Successfully navigate to destination",
                "Purchase correct ticket or fare",
                "Understand schedule and timing",
                "Ask for help when needed",
                "Handle unexpected delays",
            ],
        )

    @staticmethod

    @staticmethod
    def create_home_neighborhood_template() -> UniversalScenarioTemplate:
        """Create home and neighborhood template"""
        return UniversalScenarioTemplate(
            template_id="home_neighborhood",
            name="Home and Neighborhood",
            category=ScenarioCategory.DAILY_LIFE,
            tier=1,
            base_vocabulary=[
                "home",
                "house",
                "apartment",
                "building",
                "neighborhood",
                "street",
                "address",
                "mailbox",
                "key",
                "door",
                "window",
                "garden",
                "yard",
                "neighbor",
                "landlord",
                "rent",
                "utilities",
                "electricity",
                "water",
                "heating",
                "air conditioning",
                "furniture",
                "kitchen",
                "bathroom",
                "bedroom",
            ],
            essential_phrases={
                "beginner": [
                    "I live in...",
                    "My address is...",
                    "Where do you live?",
                    "Is this a good neighborhood?",
                    "How long have you lived here?",
                    "I like my apartment",
                ],
                "intermediate": [
                    "What's the neighborhood like?",
                    "Are there good schools nearby?",
                    "Is it safe to walk at night?",
                    "Where's the closest grocery store?",
                    "How's the public transportation?",
                    "The rent is reasonable",
                ],
                "advanced": [
                    "What amenities are available in the area?",
                    "How's the cost of living here?",
                    "Are there any noise issues?",
                    "What's the community like?",
                    "Are there local events or activities?",
                    "I'm thinking of buying in this area",
                ],
            },
            cultural_context={
                "notes": "Living arrangements and neighborhood concepts vary culturally. Some cultures emphasize community, others privacy.",
                "housing_types": [
                    "single_family",
                    "apartment",
                    "condo",
                    "shared_housing",
                ],
                "community_aspects": [
                    "neighborhood_watch",
                    "local_events",
                    "shared_spaces",
                ],
                "privacy_norms": [
                    "close_neighbors",
                    "distant_neighbors",
                    "community_involvement",
                ],
            },
            learning_objectives=[
                "Describe living situation and home",
                "Discuss neighborhood characteristics",
                "Ask about local amenities and services",
                "Express preferences about housing",
                "Navigate housing-related conversations",
            ],
            conversation_starters=[
                "Do you live around here?",
                "What's this area like?",
                "I'm new to the neighborhood",
                "Can you recommend any local places?",
                "How do you like living here?",
            ],
            scenario_variations=[
                {
                    "id": "new_resident",
                    "description": "Just moved to a new area",
                    "setting": "New neighborhood exploration",
                    "phases": [
                        "area_orientation",
                        "neighbor_introductions",
                        "local_services",
                        "community_integration",
                    ],
                },
                {
                    "id": "house_hunting",
                    "description": "Looking for a new place to live",
                    "setting": "Apartment viewing or house hunting",
                    "phases": [
                        "location_discussion",
                        "property_features",
                        "neighborhood_assessment",
                        "decision_making",
                    ],
                },
                {
                    "id": "neighbor_chat",
                    "description": "Casual conversation with neighbors",
                    "setting": "Building hallway, garden, or local area",
                    "phases": [
                        "friendly_greeting",
                        "local_updates",
                        "shared_concerns",
                        "future_interactions",
                    ],
                },
            ],
            difficulty_modifiers={
                "beginner": {"duration": 10, "phase_duration": 3, "vocab_limit": 15},
                "intermediate": {
                    "duration": 15,
                    "phase_duration": 4,
                    "vocab_limit": 20,
                },
                "advanced": {"duration": 20, "phase_duration": 5, "vocab_limit": 25},
            },
            success_metrics=[
                "Describe home and living situation",
                "Discuss neighborhood features",
                "Ask relevant questions about area",
                "Express housing preferences",
                "Build neighborly relationships",
            ],
        )


    @staticmethod
    def get_tier1_templates() -> List[UniversalScenarioTemplate]:
        """Get all Tier 1 templates"""
        return [
            ScenarioTemplates.create_greetings_template(),
            ScenarioTemplates.create_family_template(),
            ScenarioTemplates.create_restaurant_template(),
            ScenarioTemplates.create_transportation_template(),
            ScenarioTemplates.create_home_neighborhood_template(),
        ]

    @staticmethod
    def get_tier2_templates() -> List[UniversalScenarioTemplate]:
        """Get all Tier 2 templates"""
        return [
            ScenarioTemplates.create_daily_routine_template(),
            ScenarioTemplates.create_basic_conversations_template(),
        ]
