"""Add content persistence tables (processed_content, learning_materials)

Revision ID: a358c11bb177
Revises: 103bff5401ca
Create Date: 2025-12-17 14:03:54.371524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a358c11bb177'
down_revision: Union[str, Sequence[str], None] = '103bff5401ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('processed_content', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('processing_stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processed_content_created', 'processed_content', ['created_at'], unique=False)
    op.create_index('idx_processed_content_language', 'processed_content', ['language'], unique=False)
    op.create_index('idx_processed_content_type', 'processed_content', ['content_type'], unique=False)
    op.create_index('idx_processed_content_user', 'processed_content', ['user_id'], unique=False)
    op.create_index(op.f('ix_processed_content_content_id'), 'processed_content', ['content_id'], unique=True)
    op.create_table('learning_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.String(length=100), nullable=False),
    sa.Column('content_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['processed_content.content_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_learning_materials_content', 'learning_materials', ['content_id'], unique=False)
    op.create_index('idx_learning_materials_created', 'learning_materials', ['created_at'], unique=False)
    op.create_index('idx_learning_materials_type', 'learning_materials', ['material_type'], unique=False)
    op.create_index('idx_learning_materials_user', 'learning_materials', ['user_id'], unique=False)
    op.create_index(op.f('ix_learning_materials_material_id'), 'learning_materials', ['material_id'], unique=True)
    op.drop_table('admin_language_config')
    op.drop_table('conversation_metrics')
    op.drop_index('idx_sessions_date', table_name='learning_sessions_old')
    op.drop_index('idx_sessions_type', table_name='learning_sessions_old')
    op.drop_index('idx_sessions_user_language', table_name='learning_sessions_old')
    op.drop_table('learning_sessions_old')
    op.drop_table('skill_progress_metrics')
    op.drop_index('idx_reset_log_timestamp', table_name='budget_reset_log')
    op.drop_index('idx_reset_log_user_id', table_name='budget_reset_log')
    op.drop_table('budget_reset_log')
    op.drop_index('idx_goals_target_date', table_name='learning_goals')
    op.drop_index('idx_goals_user_status', table_name='learning_goals')
    op.drop_table('learning_goals')
    op.drop_table('learning_path_recommendations')
    op.drop_table('voice_models')
    op.drop_index('ix_simple_users_user_id', table_name='simple_users')
    op.drop_table('simple_users')
    op.drop_index('idx_budget_period_end', table_name='user_budget_settings')
    op.drop_index('idx_budget_user_id', table_name='user_budget_settings')
    op.drop_table('user_budget_settings')
    op.drop_index('idx_sr_items_mastery', table_name='spaced_repetition_items')
    op.drop_index('idx_sr_items_review_date', table_name='spaced_repetition_items')
    op.drop_index('idx_sr_items_type', table_name='spaced_repetition_items')
    op.drop_index('idx_sr_items_user_language', table_name='spaced_repetition_items')
    op.drop_table('spaced_repetition_items')
    op.drop_index('idx_analytics_type_date', table_name='learning_analytics')
    op.drop_index('idx_analytics_user_period', table_name='learning_analytics')
    op.drop_table('learning_analytics')
    op.drop_table('admin_spaced_repetition_config')
    op.drop_index('idx_streaks_activity_date', table_name='learning_streaks')
    op.drop_index('idx_streaks_user_language', table_name='learning_streaks')
    op.drop_table('learning_streaks')
    op.drop_index('idx_achievements_earned', table_name='gamification_achievements')
    op.drop_index('idx_achievements_type', table_name='gamification_achievements')
    op.drop_index('idx_achievements_user', table_name='gamification_achievements')
    op.drop_table('gamification_achievements')
    op.drop_table('admin_feature_toggles')
    op.drop_table('memory_retention_analysis')
    op.alter_column('languages', 'support_level',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('FULL', 'STT_ONLY', 'FUTURE', name='supportlevel'),
               nullable=False,
               existing_server_default=sa.text("'FULL'"))
    op.alter_column('learning_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('learning_sessions', 'accuracy_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('learning_sessions', 'session_metadata',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('scenario_progress_history', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('scenario_progress_history', 'vocabulary_mastered',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('scenario_progress_history', 'objectives_completed',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('scenario_progress_history', 'success_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('scenario_progress_history', 'completion_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.add_column('user_languages', sa.Column('language_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_languages', 'languages', ['language_id'], ['id'])
    op.drop_column('user_languages', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_languages', sa.Column('language', sa.VARCHAR(length=10), nullable=False))
    op.drop_constraint(None, 'user_languages', type_='foreignkey')
    op.drop_column('user_languages', 'language_id')
    op.alter_column('scenario_progress_history', 'completion_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('scenario_progress_history', 'success_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('scenario_progress_history', 'objectives_completed',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scenario_progress_history', 'vocabulary_mastered',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scenario_progress_history', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('learning_sessions', 'session_metadata',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('learning_sessions', 'accuracy_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('learning_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('languages', 'support_level',
               existing_type=sa.Enum('FULL', 'STT_ONLY', 'FUTURE', name='supportlevel'),
               type_=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'FULL'"))
    op.create_table('memory_retention_analysis',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.TEXT(), nullable=False),
    sa.Column('analysis_period_days', sa.INTEGER(), server_default=sa.text('(30)'), nullable=True),
    sa.Column('short_term_retention_rate', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('medium_term_retention_rate', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('long_term_retention_rate', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('active_recall_success_rate', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('passive_review_success_rate', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('recall_vs_recognition_ratio', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('forgetting_curve_steepness', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('optimal_review_timing', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('interference_patterns', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('most_retained_item_types', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('least_retained_item_types', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('retention_by_difficulty', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('retention_by_context', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('average_exposures_to_master', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('efficiency_compared_to_peers', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('learning_velocity', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('optimal_study_schedule', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('retention_improvement_strategies', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('analysis_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('next_analysis_due', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language_code', 'analysis_date')
    )
    op.create_table('admin_feature_toggles',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('feature_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'general'"), nullable=True),
    sa.Column('requires_restart', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('min_role', sa.VARCHAR(length=20), server_default=sa.text("'CHILD'"), nullable=True),
    sa.Column('configuration', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamification_achievements',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('achievement_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('achievement_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('badge_icon', sa.VARCHAR(length=100), nullable=True),
    sa.Column('badge_color', sa.VARCHAR(length=20), server_default=sa.text("'#FFD700'"), nullable=True),
    sa.Column('points_awarded', sa.INTEGER(), server_default=sa.text('(10)'), nullable=True),
    sa.Column('criteria_met', sqlite.JSON(), nullable=False),
    sa.Column('required_criteria', sqlite.JSON(), nullable=False),
    sa.Column('rarity', sa.VARCHAR(length=20), server_default=sa.text("'common'"), nullable=True),
    sa.Column('earned_in_session', sa.VARCHAR(length=100), nullable=True),
    sa.Column('earned_activity', sa.VARCHAR(length=100), nullable=True),
    sa.Column('milestone_level', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('earned_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['earned_in_session'], ['learning_sessions_old.session_id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_achievements_user', 'gamification_achievements', ['user_id'], unique=False)
    op.create_index('idx_achievements_type', 'gamification_achievements', ['achievement_type'], unique=False)
    op.create_index('idx_achievements_earned', 'gamification_achievements', ['earned_at'], unique=False)
    op.create_table('learning_streaks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('current_streak', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('longest_streak', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_active_days', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_activity_date', sa.DATE(), nullable=True),
    sa.Column('streak_start_date', sa.DATE(), nullable=True),
    sa.Column('longest_streak_start', sa.DATE(), nullable=True),
    sa.Column('longest_streak_end', sa.DATE(), nullable=True),
    sa.Column('weekly_goal_days', sa.INTEGER(), server_default=sa.text('5'), nullable=True),
    sa.Column('monthly_goal_days', sa.INTEGER(), server_default=sa.text('(20)'), nullable=True),
    sa.Column('streak_freeze_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('max_freeze_count', sa.INTEGER(), server_default=sa.text('3'), nullable=True),
    sa.Column('avg_daily_minutes', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('avg_daily_accuracy', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('total_streak_points', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language_code')
    )
    op.create_index('idx_streaks_user_language', 'learning_streaks', ['user_id', 'language_code'], unique=False)
    op.create_index('idx_streaks_activity_date', 'learning_streaks', ['last_activity_date'], unique=False)
    op.create_table('admin_spaced_repetition_config',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('config_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('config_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('initial_ease_factor', sa.REAL(), server_default=sa.text('(2.5)'), nullable=True),
    sa.Column('minimum_ease_factor', sa.REAL(), server_default=sa.text('(1.3)'), nullable=True),
    sa.Column('maximum_ease_factor', sa.REAL(), server_default=sa.text('(3.0)'), nullable=True),
    sa.Column('ease_factor_change', sa.REAL(), server_default=sa.text('(0.15)'), nullable=True),
    sa.Column('initial_interval_days', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('graduation_interval_days', sa.INTEGER(), server_default=sa.text('4'), nullable=True),
    sa.Column('easy_interval_days', sa.INTEGER(), server_default=sa.text('7'), nullable=True),
    sa.Column('maximum_interval_days', sa.INTEGER(), server_default=sa.text('(365)'), nullable=True),
    sa.Column('mastery_threshold', sa.REAL(), server_default=sa.text('(0.85)'), nullable=True),
    sa.Column('review_threshold', sa.REAL(), server_default=sa.text('(0.7)'), nullable=True),
    sa.Column('difficulty_threshold', sa.REAL(), server_default=sa.text('(0.5)'), nullable=True),
    sa.Column('retention_threshold', sa.REAL(), server_default=sa.text('(0.8)'), nullable=True),
    sa.Column('points_per_correct', sa.REAL(), server_default=sa.text('(10)'), nullable=True),
    sa.Column('points_per_streak_day', sa.REAL(), server_default=sa.text('5'), nullable=True),
    sa.Column('points_per_goal_achieved', sa.REAL(), server_default=sa.text('(100)'), nullable=True),
    sa.Column('daily_goal_default', sa.INTEGER(), server_default=sa.text('(30)'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('applies_to_language', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_by_admin', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['applies_to_language'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['created_by_admin'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_analytics',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_period', sa.VARCHAR(length=20), nullable=False),
    sa.Column('total_study_time_minutes', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('sessions_completed', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('avg_session_duration_minutes', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('items_studied', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('items_learned', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('items_reviewed', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('overall_accuracy', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('avg_response_time_ms', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('mastery_improvements', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('streak_days', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('goals_achieved', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('skill_level_gains', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('avg_engagement_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('feature_usage', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('preferred_study_times', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('percentile_rank', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('improvement_rate', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('consistency_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('calculated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language_code', 'metric_type', 'date_period')
    )
    op.create_index('idx_analytics_user_period', 'learning_analytics', ['user_id', 'date_period'], unique=False)
    op.create_index('idx_analytics_type_date', 'learning_analytics', ['metric_type', 'date_period'], unique=False)
    op.create_table('spaced_repetition_items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('translation', sa.TEXT(), nullable=True),
    sa.Column('definition', sa.TEXT(), nullable=True),
    sa.Column('pronunciation_guide', sa.TEXT(), nullable=True),
    sa.Column('example_usage', sa.TEXT(), nullable=True),
    sa.Column('context_tags', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('difficulty_level', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('ease_factor', sa.REAL(), server_default=sa.text('(2.5)'), nullable=True),
    sa.Column('repetition_number', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('interval_days', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('last_review_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('next_review_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('correct_reviews', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('incorrect_reviews', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('streak_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('mastery_level', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('confidence_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('first_seen_date', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_studied_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('average_response_time_ms', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('learning_speed_factor', sa.REAL(), server_default=sa.text('(1.0)'), nullable=True),
    sa.Column('retention_rate', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('source_session_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('source_content', sa.VARCHAR(length=100), nullable=True),
    sa.Column('metadata', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['source_session_id'], ['learning_sessions_old.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language_code', 'content', 'item_type')
    )
    op.create_index('idx_sr_items_user_language', 'spaced_repetition_items', ['user_id', 'language_code'], unique=False)
    op.create_index('idx_sr_items_type', 'spaced_repetition_items', ['item_type'], unique=False)
    op.create_index('idx_sr_items_review_date', 'spaced_repetition_items', ['next_review_date'], unique=False)
    op.create_index('idx_sr_items_mastery', 'spaced_repetition_items', ['mastery_level'], unique=False)
    op.create_table('user_budget_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('monthly_limit_usd', sa.FLOAT(), nullable=False),
    sa.Column('custom_limit_usd', sa.FLOAT(), nullable=True),
    sa.Column('budget_period', sa.VARCHAR(length=7), nullable=False),
    sa.Column('custom_period_days', sa.INTEGER(), nullable=True),
    sa.Column('current_period_start', sa.DATETIME(), nullable=False),
    sa.Column('current_period_end', sa.DATETIME(), nullable=True),
    sa.Column('last_reset_date', sa.DATETIME(), nullable=False),
    sa.Column('enforce_budget', sa.BOOLEAN(), nullable=False),
    sa.Column('allow_budget_override', sa.BOOLEAN(), nullable=False),
    sa.Column('auto_fallback_to_ollama', sa.BOOLEAN(), nullable=False),
    sa.Column('alert_threshold_yellow', sa.FLOAT(), nullable=False),
    sa.Column('alert_threshold_orange', sa.FLOAT(), nullable=False),
    sa.Column('alert_threshold_red', sa.FLOAT(), nullable=False),
    sa.Column('budget_visible_to_user', sa.BOOLEAN(), nullable=False),
    sa.Column('user_can_modify_limit', sa.BOOLEAN(), nullable=False),
    sa.Column('user_can_reset_budget', sa.BOOLEAN(), nullable=False),
    sa.Column('admin_notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('configured_by', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_budget_user_id', 'user_budget_settings', ['user_id'], unique=False)
    op.create_index('idx_budget_period_end', 'user_budget_settings', ['current_period_end'], unique=False)
    op.create_table('simple_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('role', sa.VARCHAR(length=6), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('ui_language', sa.VARCHAR(length=10), server_default=sa.text("'en'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simple_users_user_id', 'simple_users', ['user_id'], unique=1)
    op.create_table('voice_models',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('config_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('quality_level', sa.VARCHAR(length=20), server_default=sa.text("'medium'"), nullable=True),
    sa.Column('sample_rate', sa.INTEGER(), server_default=sa.text('(22050)'), nullable=True),
    sa.Column('file_size_mb', sa.REAL(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_path_recommendations',
    sa.Column('recommendation_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.TEXT(), nullable=False),
    sa.Column('recommended_path_type', sa.TEXT(), nullable=False),
    sa.Column('path_title', sa.TEXT(), nullable=False),
    sa.Column('path_description', sa.TEXT(), nullable=True),
    sa.Column('estimated_duration_weeks', sa.INTEGER(), server_default=sa.text('(12)'), nullable=True),
    sa.Column('difficulty_level', sa.INTEGER(), server_default=sa.text('2'), nullable=True),
    sa.Column('recommendation_reasons', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('user_strengths', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('user_weaknesses', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('learning_style_preferences', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('primary_goals', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('weekly_milestones', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('success_metrics', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('time_commitment_hours_per_week', sa.REAL(), server_default=sa.text('(5.0)'), nullable=True),
    sa.Column('preferred_session_length_minutes', sa.INTEGER(), server_default=sa.text('(30)'), nullable=True),
    sa.Column('optimal_practice_times', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('confidence_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('expected_success_rate', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('adaptation_triggers', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('learning_goals',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('goal_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('goal_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('target_value', sa.REAL(), nullable=False),
    sa.Column('current_value', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=False),
    sa.Column('difficulty_level', sa.INTEGER(), server_default=sa.text('2'), nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('2'), nullable=True),
    sa.Column('is_daily', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_weekly', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_monthly', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('progress_percentage', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('milestones_reached', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_milestones', sa.INTEGER(), server_default=sa.text('5'), nullable=True),
    sa.Column('last_progress_update', sa.TIMESTAMP(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('target_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('completed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goals_user_status', 'learning_goals', ['user_id', 'status'], unique=False)
    op.create_index('idx_goals_target_date', 'learning_goals', ['target_date'], unique=False)
    op.create_table('budget_reset_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('reset_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('reset_by', sa.VARCHAR(length=50), nullable=True),
    sa.Column('previous_limit', sa.FLOAT(), nullable=False),
    sa.Column('new_limit', sa.FLOAT(), nullable=False),
    sa.Column('previous_spent', sa.FLOAT(), nullable=False),
    sa.Column('previous_period_start', sa.DATETIME(), nullable=False),
    sa.Column('previous_period_end', sa.DATETIME(), nullable=False),
    sa.Column('new_period_start', sa.DATETIME(), nullable=False),
    sa.Column('new_period_end', sa.DATETIME(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=500), nullable=True),
    sa.Column('reset_timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reset_log_user_id', 'budget_reset_log', ['user_id'], unique=False)
    op.create_index('idx_reset_log_timestamp', 'budget_reset_log', ['reset_timestamp'], unique=False)
    op.create_table('skill_progress_metrics',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.TEXT(), nullable=False),
    sa.Column('skill_type', sa.TEXT(), nullable=False),
    sa.Column('current_level', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('mastery_percentage', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('confidence_level', sa.TEXT(), server_default=sa.text("'moderate'"), nullable=True),
    sa.Column('initial_assessment_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('latest_assessment_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('total_improvement', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('improvement_rate', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('total_practice_sessions', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_practice_time_minutes', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('average_session_performance', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('consistency_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('easy_items_percentage', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('moderate_items_percentage', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('hard_items_percentage', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('challenge_comfort_level', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('retention_rate', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('forgetting_curve_analysis', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('optimal_review_intervals', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('recommended_focus_areas', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('suggested_exercises', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('next_milestone_target', sa.TEXT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('next_assessment_due', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language_code', 'skill_type')
    )
    op.create_table('learning_sessions_old',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('session_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('mode_specific_data', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('items_studied', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('items_correct', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('items_incorrect', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('accuracy_percentage', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('average_response_time_ms', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('confidence_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('engagement_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('difficulty_level', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('new_items_learned', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('items_reviewed', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('streak_contributions', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('goal_progress', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('content_source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ai_model_used', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tutor_mode', sa.VARCHAR(length=50), nullable=True),
    sa.Column('scenario_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_user_language', 'learning_sessions_old', ['user_id', 'language_code'], unique=False)
    op.create_index('idx_sessions_type', 'learning_sessions_old', ['session_type'], unique=False)
    op.create_index('idx_sessions_date', 'learning_sessions_old', ['started_at'], unique=False)
    op.create_table('conversation_metrics',
    sa.Column('session_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.TEXT(), nullable=False),
    sa.Column('conversation_type', sa.TEXT(), nullable=False),
    sa.Column('scenario_id', sa.TEXT(), nullable=True),
    sa.Column('tutor_mode', sa.TEXT(), nullable=True),
    sa.Column('duration_minutes', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('total_exchanges', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('user_turns', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('ai_turns', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('words_spoken', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('unique_words_used', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('vocabulary_complexity_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('grammar_accuracy_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('pronunciation_clarity_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('fluency_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('average_confidence_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('confidence_distribution', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('engagement_score', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('hesitation_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('self_correction_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('new_vocabulary_encountered', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('grammar_patterns_practiced', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('cultural_context_learned', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('learning_objectives_met', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('improvement_from_last_session', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('peer_comparison_percentile', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('started_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('admin_language_config',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('language_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_enabled_globally', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('default_voice_model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('speech_recognition_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('text_to_speech_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('pronunciation_analysis_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('conversation_mode_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('tutor_mode_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('scenario_mode_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('realtime_analysis_enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('difficulty_levels', sqlite.JSON(), server_default=sa.text('\'["beginner", "intermediate", "advanced"]\''), nullable=True),
    sa.Column('voice_settings', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['default_voice_model'], ['voice_models.model_name'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code')
    )
    op.drop_index(op.f('ix_learning_materials_material_id'), table_name='learning_materials')
    op.drop_index('idx_learning_materials_user', table_name='learning_materials')
    op.drop_index('idx_learning_materials_type', table_name='learning_materials')
    op.drop_index('idx_learning_materials_created', table_name='learning_materials')
    op.drop_index('idx_learning_materials_content', table_name='learning_materials')
    op.drop_table('learning_materials')
    op.drop_index(op.f('ix_processed_content_content_id'), table_name='processed_content')
    op.drop_index('idx_processed_content_user', table_name='processed_content')
    op.drop_index('idx_processed_content_type', table_name='processed_content')
    op.drop_index('idx_processed_content_language', table_name='processed_content')
    op.drop_index('idx_processed_content_created', table_name='processed_content')
    op.drop_table('processed_content')
    # ### end Alembic commands ###
