"""Add simple_users table for authentication

Revision ID: cbb0c3ec84ad
Revises: d96993bc16a4
Create Date: 2025-08-26 21:15:46.941838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb0c3ec84ad'
down_revision: Union[str, Sequence[str], None] = 'd96993bc16a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### Create simple_users table for authentication ###
    op.create_table('simple_users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.String(length=50), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('password_hash', sa.String(length=255), nullable=True),
        sa.Column('role', sa.Enum('PARENT', 'CHILD', 'ADMIN', name='userrole'), nullable=False),
        sa.Column('first_name', sa.String(length=100), nullable=True),
        sa.Column('last_name', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('is_verified', sa.Boolean(), nullable=True, default=False),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
        sa.UniqueConstraint('email')
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user_languages', sa.Column('language_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'user_languages', 'languages', ['language_id'], ['id'])
    # op.drop_column('user_languages', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### Drop simple_users table ###
    op.drop_table('simple_users')
    
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user_languages', sa.Column('language', sa.VARCHAR(length=10), nullable=False))
    # op.drop_constraint(None, 'user_languages', type_='foreignkey')
    # op.drop_column('user_languages', 'language_id')
    # ### end Alembic commands ###
