"""Initial schema creation

Revision ID: d96993bc16a4
Revises: 
Create Date: 2025-08-25 19:42:55.236430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96993bc16a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('has_speech_support', sa.Boolean(), nullable=True),
    sa.Column('has_tts_support', sa.Boolean(), nullable=True),
    sa.Column('speech_api_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('PARENT', 'CHILD', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('ui_language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('privacy_settings', sa.JSON(), nullable=True),
    sa.Column('parental_controls', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_created', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_provider', sa.String(length=50), nullable=False),
    sa.Column('api_endpoint', sa.String(length=100), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('response_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_usage_date', 'api_usage', ['created_at'], unique=False)
    op.create_index('idx_api_usage_provider', 'api_usage', ['api_provider'], unique=False)
    op.create_index('idx_api_usage_user', 'api_usage', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_active', 'conversations', ['is_active'], unique=False)
    op.create_index('idx_conversation_started', 'conversations', ['started_at'], unique=False)
    op.create_index('idx_conversation_user_language', 'conversations', ['user_id', 'language'], unique=False)
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.Enum('PDF', 'DOCX', 'PPTX', 'TXT', 'URL', 'YOUTUBE', name='documenttype'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('processed_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_metadata', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('key_topics', sa.JSON(), nullable=True),
    sa.Column('vocabulary_extracted', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_processed', 'documents', ['is_processed'], unique=False)
    op.create_index('idx_document_uploaded', 'documents', ['uploaded_at'], unique=False)
    op.create_index('idx_document_user_type', 'documents', ['user_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=True)
    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('skill_type', sa.String(length=50), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('target_level', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('total_study_time_minutes', sa.Integer(), nullable=True),
    sa.Column('sessions_completed', sa.Integer(), nullable=True),
    sa.Column('words_learned', sa.Integer(), nullable=True),
    sa.Column('conversations_completed', sa.Integer(), nullable=True),
    sa.Column('average_accuracy', sa.Float(), nullable=True),
    sa.Column('improvement_rate', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'MASTERED', name='learningstatus'), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language', 'skill_type', name='uq_user_language_skill')
    )
    op.create_index('idx_progress_status', 'learning_progress', ['status'], unique=False)
    op.create_index('idx_progress_user_language', 'learning_progress', ['user_id', 'language'], unique=False)
    op.create_table('user_languages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'language')
    )
    op.create_table('vocabulary_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('translation', sa.String(length=255), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('pronunciation', sa.String(length=255), nullable=True),
    sa.Column('phonetic_transcription', sa.String(length=255), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('frequency_score', sa.Float(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('times_studied', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('times_incorrect', sa.Integer(), nullable=True),
    sa.Column('mastery_level', sa.Float(), nullable=True),
    sa.Column('example_sentences', sa.JSON(), nullable=True),
    sa.Column('context_tags', sa.JSON(), nullable=True),
    sa.Column('source_document_id', sa.String(length=100), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('repetition_interval_days', sa.Integer(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('first_learned', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language', 'word', name='uq_user_language_word')
    )
    op.create_index('idx_vocab_mastery', 'vocabulary_items', ['mastery_level'], unique=False)
    op.create_index('idx_vocab_review_date', 'vocabulary_items', ['next_review_date'], unique=False)
    op.create_index('idx_vocab_user_language', 'vocabulary_items', ['user_id', 'language'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='conversationrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('pronunciation_feedback', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('vocabulary_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation_role', 'conversation_messages', ['conversation_id', 'role'], unique=False)
    op.create_index('idx_message_created', 'conversation_messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_created', table_name='conversation_messages')
    op.drop_index('idx_message_conversation_role', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('idx_vocab_user_language', table_name='vocabulary_items')
    op.drop_index('idx_vocab_review_date', table_name='vocabulary_items')
    op.drop_index('idx_vocab_mastery', table_name='vocabulary_items')
    op.drop_table('vocabulary_items')
    op.drop_table('user_languages')
    op.drop_index('idx_progress_user_language', table_name='learning_progress')
    op.drop_index('idx_progress_status', table_name='learning_progress')
    op.drop_table('learning_progress')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_index('idx_document_user_type', table_name='documents')
    op.drop_index('idx_document_uploaded', table_name='documents')
    op.drop_index('idx_document_processed', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_index('idx_conversation_user_language', table_name='conversations')
    op.drop_index('idx_conversation_started', table_name='conversations')
    op.drop_index('idx_conversation_active', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_api_usage_user', table_name='api_usage')
    op.drop_index('idx_api_usage_provider', table_name='api_usage')
    op.drop_index('idx_api_usage_date', table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_created', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
